### ISSUE TITLE
on OSX, eyaml isn't expanding `~` into /Users/$USER

### ISSUE THREAD

**Issue by dkowis** [voxpupuli/hiera-eyaml#170]
... for any of the configured paths. It's using the current working directory and making a "~" directory in there.

This makes it super risky to delete because `rm -r ~` does properly expand. Super nervous.

This is version 2.0.8, btw.

**Comment by sfable** [comment]
I've got a similar issue on fedora 21 with config file entries:
`pkcs7_public_key: '~/eyaml/keys/public_key.pkcs7.pem'`
returns:
`[hiera-eyaml-core] No such file or directory @ rb_sysopen - ~/eyaml/keys/public_key.pkcs7.pem`
version: 2.0.8
Ruby version: 2.1.6p336

**Comment by TomPoulton** [comment]
This is a known issue that I came across when I was testing on my Mac. I'll keep the issue open and try to get a fix pushed out at some point

**Comment by SirDice** [comment]
Bug's been open for almost 2 years. Issue isn't restricted to OS-X (or any other OS). 

```[root@blah ~]# eyaml edit test.eyaml
[hiera-eyaml-core] Loaded config from /root/.eyaml/config.yaml
[hiera-eyaml-core] test.eyaml doesn't exist, editing new file
[hiera-eyaml-core] No such file or directory - ~/keys/public_key.pkcs7.pem
```
This is on a recent RHEL7. Issue remains.

Either fix the documention (because that tells you to use ~) or actually fix the issue.

**Comment by rnelson0** [comment]
Oh, dear. Tilde is a shell expansion, that really shouldn't be suggested in the docs. Thank you for bumping this, I'll look at udpating docs!

**Comment by gepandz** [comment]
Is there a way to request that feature? I'd love to be able to pass around a generalized config file that uses `~/keys/` instead of having to tell my team to "Make sure you update your `~/.eyaml/config.yaml` file to point to your own, personal, home directory before you actually try to use this," or have to explain that "You need to be sure you're in the right relative directory, lest nothing work"...

Thanks!

**Comment by rnelson0** [comment]
@gepandz Possibly, but I think it needs a new issue as it's not an OSX thing, and will require more than doc updates.
